### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by RushilShaw** [Boilergrams/Boilergrams#1]
To whomever is working on an issue - claim the issue in the comment and/or create a branch. 
Thanks for your help! I hope to get this website deployed before January 5th.

- [x] Fix Color Scheme
I believe we should hold off on this one util we are in a more ready state. I hope to make it look more Purdue Themed but I'm open for suggestions.
```
Code can be found:

let backgroundColor = "bg-white";
if (isSelected && isModifiable) {
	backgroundColor = "bg-yellow-200";
} else if (isModifiable) {
	backgroundColor = "bg-gray-200";
} else if (!isModifiable && cell.letter) {
	backgroundColor = "bg-gray-300";
}

Also the background of the website should be changed in index.tsx not the GridGame
``` 

- [x] Add timer
Timer should start when game is started either a start button or when the page loads, and should end when the game is complete.
We should probably have a signal that is a "is_game_complete" boolean, but I'll leave this up to the developer.

- [x] Add Tries
There should be a counter that lets us know how many submits/checks the user has left. Also create a tries runs out state where the correct answers are revealed.

- [x] Deploy on ~~AWS~~ Deno Deploy apparently
- [x] Make used characters less visible
Currently it is confusing which letters have been used. The current strikethrough method is not terribly effective. I was thinking that we gray the used characters out. Alternatively we could sort them till the end. However, I am much more open to suggestions on this.

- [x] Optimize the codebase
Using chatGPT is great for making a functioning codebase quickly, but the code quality is pretty bad, especially the handleKeyPress function. (THANK-YOU MICHAEL)

- [ ] Make an endless mode, unlike wordle (This should be very backlog)
- [ ] Add in a share button (is there an api that lets us go stright to the messages app like how instagram reels does it?)
- [x] #11
- [x] Get Rid of the Random Blue Box when selecting the grid
- [ ] https://docs.deno.com/deploy/manual/edge-cache/ Add edge-caching
